# Generated by Django 2.2.28 on 2023-01-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='application',
        ),
    ]
