# Generated by Django 2.2.28 on 2023-01-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile')], default='None', max_length=50)),
                ('framework', models.CharField(choices=[('DJANGO', 'Django'), ('REACT', 'React')], default='None', max_length=50)),
                ('domain_name', models.CharField(max_length=50)),
            ],
        ),
    ]
