# Generated by Django 2.2.28 on 2023-01-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='domain_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
