# Generated by Django 2.2.28 on 2023-01-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230120_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='domain_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
